version: '3.9'

services:
  mysql:
    
    restart: always
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: inventario
    networks:
      - spring-red
    volumes:
      - mysql-data:/var/lib/mysql
    
  springboot:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/inventario?autoReconnect=true&ssl=false  
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - spring-red
networks:
  spring-red:
volumes:
  mysql-data: